openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
tags:
  - name: user
  - name: product
paths:
  /api/users/findAll:
    get:
      tags:
        - user
      responses:
        "200":
          description: OK

  /api/users/findById/{id}:
    get:
      tags:
        - user
      parameters:
        - name: id
          in: path
      responses:
        "200":
          description: OK

  /api/users/create:
    post:
      tags:
        - user
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: OK

  /api/products/findAll:
    get:
      tags:
        - product
      responses:
        "200":
          description: OK

  /api/products/create:
    post:
      tags:
        - product
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                product_id:
                  type: integer
                reorder_level:
                  type: integer
                barcode:
                  type: integer
                product_name:
                  type: string
                unit_id: 
                  type: integer
                product_unit_in_stock: 
                  type: integer
                category_id:
                  type: integer
                user_id:
                  type: integer
                product_unit_price:
                  type: integer
                product_short_name:
                  type: string
                product_discount:
                  type: integer

      responses:
        "200":
          description: OK
