openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
tags:
  - name: user
  - name: product
  - name: product_category
  - name: store
  - name: stock
  - name: transaction
paths:
  /api/store/findAll:
    get:
      tags:
        - store
      responses:
        "200":
          description: OK
  /api/store/create:
    post:
      tags:
        - store
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                address:
                  type: string
      responses:
        "200":
          description: OK

  /api/users/findAll:
    get:
      tags:
        - user
      responses:
        "200":
          description: OK

  /api/users/findById/{id}:
    get:
      tags:
        - user
      parameters:
        - name: id
          in: path
      responses:
        "200":
          description: OK

  /api/users/create:
    post:
      tags:
        - user
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: OK

  /api/products/findAll:
    get:
      tags:
        - product
      responses:
        "200":
          description: OK

  /api/products/create:
    post:
      tags:
        - product
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                product_name:
                  type: string
                price:
                  type: integer
                barcode:
                  type: string
                user_id:
                  type: integer
                product_category_id:
                  type: integer

      responses:
        "200":
          description: OK

  /api/products/update/{product_id}:
    post:
      tags:
        - product
      parameters:
        - name: product_id
          in: path
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                product_name:
                  type: string
                price:
                  type: integer
                barcode:
                  type: string
                user_id:
                  type: integer
                product_category_id:
                  type: integer
      responses:
        "200":
          description: OK

  /api/products/findById/{product_id}:
    get:
      tags:
        - product
      parameters:
        - name: product_id
          in: path
      responses:
        "200":
          description: OK
  /api/products/findByBarcode/{barcode}:
    get:
      tags:
        - product
      parameters:
        - name: barcode
          in: path
      responses:
        "200":
          description: OK

  /api/products/delete/{product_id}:
    delete:
      tags:
        - product
      parameters:
        - name: product_id
          in: path
      responses:
        "200":
          description: OK

  /api/productCategory/findAll:
    get:
      tags:
        - product_category
      responses:
        "200":
          description: OK

  /api/productCategory/create:
    post:
      tags:
        - product_category
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                product_category:
                  type: string
                enable:
                  type: boolean
      responses:
        "200":
          description: OK

  /api/productCategory/update/{product_category_id}:
    post:
      tags:
        - product_category
      parameters:
        - name: product_category_id
          in: path
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                product_category:
                  type: string
                enable:
                  type: boolean
      responses:
        "200":
          description: OK

  /api/productCategory/delete/{product_category_id}:
    delete:
      tags:
        - product_category
      parameters:
        - name: product_category_id
          in: path
      responses:
        "200":
          description: OK

  /api/stock/findAll:
    get:
      tags:
        - stock
      responses:
        "200":
          description: OK

  /api/stock/findAllProduct:
    get:
      tags:
        - stock
      responses:
        "200":
          description: OK

  /api/stock/create:
    post:
      tags:
        - stock
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                product_id:
                  type: integer
                quantity:
                  type: integer
                store_id:
                  type: integer
      responses:
        "200":
          description: OK

  /api/stock/update/{stock_id}:
    post:
      tags:
        - stock
      parameters:
        - name: stock_id
          in: path
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                product_id:
                  type: integer
                quantity:
                  type: integer
                store_id:
                  type: integer
                isEnable:
                  type: boolean
      responses:
        "200":
          description: OK

  /api/stock/quantityAdjust/{stock_id}:
    post:
      tags:
        - stock
      parameters:
        - name: stock_id
          in: path
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                product_id:
                  type: string
                quantityUpdate:
                  type: integer
      responses:
        "200":
          description: OK

  /api/stock/addStock:
    post:
      tags:
        - stock
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/AddStockList"
      responses:
        "200":
          description: OK
  /api/stock/missingStock:
    post:
      tags:
        - stock
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/MissingStockList"
      responses:
        "200":
          description: OK

  /api/transaction/findAll:
    get:
      tags:
        - transaction
      responses:
        "200":
          description: OK

  /api/transaction/create:
    post:
      tags:
        - transaction
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                product_id:
                  type: integer
                quantity:
                  type: integer
                cost:
                  type: integer
                income:
                  type: integer
      responses:
        "200":
          description: OK

components:
  schemas:
    AddStockList:
      type: object
      properties:
        product_id:
          type: string
        quantity:
          type: integer
        cost:
          type: integer
    MissingStockList:
      type: object
      properties:
        product_id:
          type: string
        quantity:
          type: integer
        income:
          type: integer
