openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
tags:
  - name: user
  - name: product
  - name: payment
paths:
  /api/users/findAll:
    get:
      tags:
        - user
      responses:
        "200":
          description: OK

  /api/users/findById/{id}:
    get:
      tags:
        - user
      parameters:
        - name: id
          in: path
      responses:
        "200":
          description: OK

  /api/users/create:
    post:
      tags:
        - user
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: OK

  /api/products/findAll:
    get:
      tags:
        - product
      responses:
        "200":
          description: OK

  /api/products/create:
    post:
      tags:
        - product
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                product_name:
                  type: string
                price:
                  type: integer
                user_id:
                  type: integer
      responses:
        "200":
          description: OK

# payment
  /api/payments/findAll:
    get:
      tags:
        - payment
      responses:
        "200":
          description: OK

  /api/payments/findById/{id}:
    get:
      tags:
        - payment
      parameters:
        - name: id
          in: path
      responses:
        "200":
          description: OK

  /api/payments/create:
    post:
      tags:
        - payment
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                payment_order_id:
                  type: integer
                user_id:
                  type: integer
                order_date:
                  type: date
                  format: date-time
                product_id:
                  type: object
                purchase_order_quantity:
                  type: integer
                purchase_order_sub_total:
                  type: integer
                purchase_order_total:
                  type: integer
                purchase_order_tax:
                  type: integer
      responses:
        "200":
          description: OK
